### ISSUE TITLE
Connect AWS to Web App

### ISSUE THREAD

**Issue by mcmastercapstone** [mcmastercapstone/EVE#2]
Can use CodeSandbox for fast iteration. Might need to make a backend server, repl.it can be used to spin up a quick backend.

**Comment by engbrianlee** [comment]
[Guide Part 2](https://medium.com/serverlessguru/serverless-real-time-reactjs-app-aws-iot-mqtt-17d023954045)
[Guide Part 2](https://medium.com/@serverlessguru/part-two-serverless-real-time-reactjs-app-aws-iot-mqtt-29cc481488b6)
